name: Syntax Check with Pylint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check_syntax:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install pylint
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Run pylint
        run: |
          pylint $(find . -name "*.py" -not -path "./venv/*")
